### ISSUE TITLE
update

### ISSUE THREAD

**Issue by saberzaid** [Knowledge-Wisdom-Understanding/recon#10]
hello, great tool 

i notice some error and also some outdated or maybe need to be fix for example , python3-impact but in the setup file it use python-impact

another thing i notice its it used ./enum4linux.pl ,its kinda old  , there is good rewrite tool of it : 

https://github.com/cddmp/enum4linux-ng

**Comment by Knowledge-Wisdom-Understanding** [comment]
Thanks! @saberzaid 
Yeah there's a lot of things that need cleaning up and I've learned a lot since I first started this project.
I haven't tried the enum4linux-ng python variant tool but it looks nice.
I don't have nearly as much free time as I used to, life kinda gets in the way.
So I haven't really been actively maintaining this project anymore. Perhaps I will find some time to make some updates that I've been meaning to implement, but feel free to make a PR (pull-request) in the meantime :) with some of your proposed changes.

**Comment by Knowledge-Wisdom-Understanding** [comment]
WUSSUP! @saberzaid ,
I had some time to update stuff, added enum4linux-ng in place of the old outdated enum4linux.
via this [commit](https://github.com/Knowledge-Wisdom-Understanding/recon/commit/78b15fba361c9c9d043938b16d8397d431989e46)
💯  👊

**Comment by saberzaid** [comment]
Hi

Thank you for your effort and update , the tool is great 

Hope there will be more features and update soon into it 

Thanks👍👍
